---
# PGDL2
- attack: "PGDL2"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "PGDL2"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml

# FGSM
- attack: "FGSM"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "FGSM"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml

# FAB
- attack: "FAB"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "FAB"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml

# PGDL2_eps15
- attack: "PGDL2_eps15"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "PGDL2_eps15"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml

# FGSM_eps00075
- attack: "FGSM_eps00075"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "FGSM_eps00075"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml

# FAB_eta20
- attack: "FAB_eta20"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "FAB_eta20"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml

# PGDL2_eps20
- attack: "PGDL2_eps20"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "PGDL2_eps20"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml

# FGSM_eps001
- attack: "FGSM_eps001"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "FGSM_eps001"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml

# FAB_eta30
- attack: "FAB_eta30"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/specrnet.yaml

- attack: "FAB_eta30"
  config: configs/adversarial_evaluation/lcnn.yaml
  attack_model_config: configs/adversarial_evaluation/rawnet3.yaml
