data:
  adversarial_attacks: [
    # "ONE_PIXEL",
    "FGSM",
    "FGSM",
    # "PGD",
    # "FAB",
    # TODO: add remaining attacks
  ]
  seed: 42

checkpoint:
  # This part is used only in evaluation (each checkpoint is used in eval on corresponding fold).
  # To ensure reliable results make sure that the order of checkpoints is correct (i.e. fold_0, fold_1, fold_2)
  path: ""

model:
  name: "lcnn"
  parameters:
    input_channels: 1
    frontend_algorithm: ["lfcc"]
  optimizer:
    lr: 0.0001

logging:
  log_metrics: True
  existing_experiment_id: ""  # specify if you want to continue certain neptune experiment
  name: "Initial adversarial training"
  description: ""
  tags: ["adversarial_training"]
