checkpoint:
  path: ./trained_models/specrnet_wavefake_22-04-2024-19-13-12/ckpt.pth
data:
  seed: 42
model:
  name: specrnet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    frontend_algorithm:
    - lfcc
    input_channels: 1
