checkpoint:
  path: /home/hanhnlh/projects/ccs/deepfakes_detectors/audio-deepfake-adversarial-attacks/trained_models/asvspoof21__specrnet__1702348725.834654/ckpt.pth
data:
  seed: 42
model:
  name: specrnet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    frontend_algorithm:
    - lfcc
    input_channels: 1
